INFO     root:data_depend.py:37 提取变量：log_id: 840994795
INFO     root:validate.py:76 响应断言:  预期值: 'success' 实际值: 'success', 断言成功!