INFO     root:data_depend.py:37 提取变量：errorFileId: 32750c80-5d63-4182-abe2-02033e1cbf1d
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!
INFO     root:validate.py:76 响应断言:  预期值: '1' 实际值: '1', 断言成功!