INFO     root:validate.py:78 响应断言:  预期值: '1' 实际值: '0', 断言失败!